name = "logistic"
uuid = "0eaa0ab2-7107-42ff-aa78-a9ac3bd058b3"
authors = ["Kohtaroh Sakaue <spikekohtaroh@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
